#!/bin/bash

echo "Installing pyenv"
wget -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash

echo "Cloning bash-it"
cd bash-it
git submodule init
git submodule update
source install.sh
bash-it enable git

cd ..
echo "Cloning spacemacs"
[ -f ~/emacs.d ] && git clone https://github.com/syl20bnr/spacemacs.git emacs.d
[ -f ~/emacs.d ] && ln -s $HOME/dotfiles/emacs.d $HOME/.emacs.d

echo "Cloning spf13-vim"
cd spf13-vim
git submodule init
git submodule update
read -p "Install spf13-vim? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    source bootstrap.sh
fi

cd ..
echo "Linking"
sh $PWD/dotsync/bin/dotsync -L
